version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_ema_vwap
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
    ports:
      - "8084:8084"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-emavwap.sqlite
      --config /freqtrade/config.json
      --strategy EmaVwapLong
